-- Estruturas base para OAuth do Mercado Pago por empresa

create table if not exists public.integracoes_empresa (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  provider text not null,
  status text not null default 'Inativa',
  conta_nome text null,
  webhook_secret text null,
  access_token text null,
  refresh_token text null,
  token_expira_em timestamptz null,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'integracoes_empresa_status_check'
      and conrelid = 'public.integracoes_empresa'::regclass
  ) then
    alter table public.integracoes_empresa
      add constraint integracoes_empresa_status_check
      check (status in ('Ativa', 'Inativa'));
  end if;
end $$;

create index if not exists integracoes_empresa_company_provider_idx
  on public.integracoes_empresa (company_id, provider);

create index if not exists integracoes_empresa_provider_status_idx
  on public.integracoes_empresa (provider, status);

create unique index if not exists integracoes_empresa_company_provider_ativa_uidx
  on public.integracoes_empresa (company_id, provider)
  where status = 'Ativa';

create table if not exists public.integracoes_eventos (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  integracao_id bigint null,
  provider text not null,
  direcao text null,
  evento_tipo text null,
  evento_id_externo text null,
  payload jsonb not null default '{}'::jsonb,
  processado boolean not null default false,
  erro text null,
  created_at timestamptz not null default now()
);

create index if not exists integracoes_eventos_company_provider_idx
  on public.integracoes_eventos (company_id, provider);

create index if not exists integracoes_eventos_integracao_idx
  on public.integracoes_eventos (integracao_id);

create index if not exists integracoes_eventos_processado_idx
  on public.integracoes_eventos (processado);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'companies'
  ) and not exists (
    select 1
    from pg_constraint
    where conname = 'integracoes_empresa_company_fk'
      and conrelid = 'public.integracoes_empresa'::regclass
  ) then
    alter table public.integracoes_empresa
      add constraint integracoes_empresa_company_fk
      foreign key (company_id)
      references public.companies(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'companies'
  ) and not exists (
    select 1
    from pg_constraint
    where conname = 'integracoes_eventos_company_fk'
      and conrelid = 'public.integracoes_eventos'::regclass
  ) then
    alter table public.integracoes_eventos
      add constraint integracoes_eventos_company_fk
      foreign key (company_id)
      references public.companies(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'integracoes_eventos_integracao_fk'
      and conrelid = 'public.integracoes_eventos'::regclass
  ) then
    alter table public.integracoes_eventos
      add constraint integracoes_eventos_integracao_fk
      foreign key (integracao_id)
      references public.integracoes_empresa(id)
      on delete set null;
  end if;
end $$;

create or replace function public.integracoes_empresa_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_integracoes_empresa_updated_at on public.integracoes_empresa;
create trigger trg_integracoes_empresa_updated_at
before update on public.integracoes_empresa
for each row
execute function public.integracoes_empresa_set_updated_at();
